@startuml

usecase 顧客レビューを書く

actor 顧客
boundary 書籍詳細ページ
entity 顧客セッション
control ログイン済みか
control ログインする
control レビューの記入ページを表示する
boundary レビューの記入ページ
entity 顧客レビュー
control 書籍レビューの長さはOKか
control 書籍評価は範囲内か
control レビュー拒否ページ
boundary レビュー拒否ページを表示する
control 確認ページを表示する
boundary 確認ページ
control レビューをモデレータへ送信

顧客 -- 書籍詳細ページ : レビューを書くボタンをクリック
書籍詳細ページ --> ログイン済みか
顧客セッション -- ログイン済みか
ログイン済みか --> ログインする : いいえ
ログインする --> レビューの記入ページを表示する
ログイン済みか --> レビューの記入ページを表示する : はい
レビューの記入ページを表示する --> レビューの記入ページ
顧客 -- レビューの記入ページ : レビューを記入して送信ボタンをクリック
レビューの記入ページ -- 書籍レビューの長さはOKか
書籍レビューの長さはOKか --> 書籍評価は範囲内か : はい
書籍レビューの長さはOKか --> レビュー拒否ページを表示する : いいえ
書籍レビューの長さはOKか -- 顧客レビュー
レビューの記入ページ -- 書籍評価は範囲内か
書籍評価は範囲内か --> 確認ページを表示する : はい
書籍評価は範囲内か --> レビュー拒否ページを表示する : いいえ
書籍評価は範囲内か -- 顧客レビュー
レビュー拒否ページを表示する --> レビュー拒否ページ
レビューの記入ページ -- 確認ページを表示する
確認ページを表示する --> 確認ページ
確認ページ --> レビューをモデレータへ送信

@enduml